@startuml

|Client|

:POST persistClassDiscussion<

partition Discussion.persistDiscussion {

  partition Discussion.createDiscussion {
      :DB.userRW().put;
  }
}

|#AntiqueWhite|Agent|
 #eebb33:get course ]
 #eebb33:update course record ]
 #eebb33:remove doc from userRW ]
stop

@enduml



[<note>Discussion]

[<receiver>POST persistClassDiscussion]->[<start>s]
[s]->[Discussion.persistDiscussion|
  [<start>s]->[Discussion.createDiscussion|
    [<start>s]->[DB.userRW().put]
    [DB.userRW().put]->[<end>e]
  ]
  [Discussion.createDiscussion]->[<end>e]
]
[Discussion.persistDiscussion]->[<end>e]
