@startuml

start
partition Discussion.getByPrefix {

    fork
        :DB.userRW().getAllByPrefix |
    fork again
        :DB.course().byPrefix |
    fork again

        partition User.getCurrentUser {
            :DB.user().get;
            if (need online?) then (Y)
                :DB.query().byId |
            endif
        }

    end fork
}
end

@enduml
