@startuml

skinparam activity {
  backgroundColor<<external>> #AAFFFF
  backgroundColor<<operation>> #EEE
}


partition Discussion.getDiscussionActivity {

  partition UserStudy.getPublicationSummary {
      (*) --> UserStudyDao.prototype.get
      --> (*)
  }
}

@enduml